-- *****************************************************************************
-- This script contains INSERT statements for populating tables with seed data
-- *****************************************************************************

insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image, interests) values ('lordgenius', '1234', 'Gordy', 'Smith', 'Lorem ipsum dolor amet mlkshk venmo semiotics kitsch, fixie cliche ramps biodiesel iceland farm-to-table pitchfork la croix pinterest XOXO. Mustache VHS taiyaki green juice, small batch pok pok blue bottle pug aesthetic tilde trust fund locavore vape.', true, 'gordy@swordfighting.com', '614-555-3456', 'sensei', 'zombies');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image, interests) values ('tommyBoy', '1234', 'Tommy', 'Callahan', 'Lorem ipsum dolor amet mlkshk venmo semiotics kitsch, fixie cliche ramps biodiesel iceland farm-to-table pitchfork la croix pinterest XOXO. Mustache VHS taiyaki green juice, small batch pok pok blue bottle pug aesthetic tilde trust fund locavore vape.', true, 'tommy@callahan.com', '419-419-0000', 'tommy', 'road trips');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image, interests) values ('happyGilmore', '1234', 'Happy', 'Gilmore', 'Lorem ipsum dolor amet mlkshk venmo semiotics kitsch, fixie cliche ramps biodiesel iceland farm-to-table pitchfork la croix pinterest XOXO. Mustache VHS taiyaki green juice, small batch pok pok blue bottle pug aesthetic tilde trust fund locavore vape.', false, 'happy@gilmore.com', '419-419-0000', 'happy', 'golf');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image, interests) values ('royalTenenbaum', '1234', 'Royal', 'Tenenbaum', 'Lorem ipsum dolor amet mlkshk venmo semiotics kitsch, fixie cliche ramps biodiesel iceland farm-to-table pitchfork la croix pinterest XOXO. Mustache VHS taiyaki green juice, small batch pok pok blue bottle pug aesthetic tilde trust fund locavore vape.', true, 'royal@tenebaum.com', '419-419-1111', 'royal', 'prominent litigation');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image, interests) values ('steveZissou', '1234', 'Stevesy', 'Zissou', 'Lorem ipsum dolor amet mlkshk venmo semiotics kitsch, fixie cliche ramps biodiesel iceland farm-to-table pitchfork la croix pinterest XOXO. Mustache VHS taiyaki green juice, small batch pok pok blue bottle pug aesthetic tilde trust fund locavore vape.', true, 'steve@zissou.com', '419-419-2222', 'stevesy', 'scuba-diving');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image, interests) values ('lukeSkywalker', '1234', 'Luke', 'Skywalker', 'Lorem ipsum dolor amet mlkshk venmo semiotics kitsch, fixie cliche ramps biodiesel iceland farm-to-table pitchfork la croix pinterest XOXO. Mustache VHS taiyaki green juice, small batch pok pok blue bottle pug aesthetic tilde trust fund locavore vape.', true, 'luke@jediKnights.com', '419-419-3333', 'skywalker', 'father-son time');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image, interests) values ('billyMadison', '1234', 'Billy', 'Madison', 'Lorem ipsum dolor amet mlkshk venmo semiotics kitsch, fixie cliche ramps biodiesel iceland farm-to-table pitchfork la croix pinterest XOXO. Mustache VHS taiyaki green juice, small batch pok pok blue bottle pug aesthetic tilde trust fund locavore vape.', false, 'billy@madison.com', '419-419-4444', 'madison', 'gen-ed, penguins');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image, interests) values ('splinter', '1234', 'Splinter', 'Rat', 'Lorem ipsum dolor amet mlkshk venmo semiotics kitsch, fixie cliche ramps biodiesel iceland farm-to-table pitchfork la croix pinterest XOXO. Mustache VHS taiyaki green juice, small batch pok pok blue bottle pug aesthetic tilde trust fund locavore vape.', true, 'splinter@sewers.com', '419-419-5555', 'splinter', 'martial arts');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image, interests) values ('danielSon', '1234', 'Daniel', 'Son', 'Lorem ipsum dolor amet mlkshk venmo semiotics kitsch, fixie cliche ramps biodiesel iceland farm-to-table pitchfork la croix pinterest XOXO. Mustache VHS taiyaki green juice, small batch pok pok blue bottle pug aesthetic tilde trust fund locavore vape.', false, 'daniel@son.com', '419-419-6666', 'danielSon', 'karate');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image, interests) values ('gordonRamsey', '1234', 'Gordon', 'Ramsey', 'Lorem ipsum dolor amet mlkshk venmo semiotics kitsch, fixie cliche ramps biodiesel iceland farm-to-table pitchfork la croix pinterest XOXO. Mustache VHS taiyaki green juice, small batch pok pok blue bottle pug aesthetic tilde trust fund locavore vape.', true, 'gordon@ramsey.com', '419-419-7777', 'gordonRamsey', 'cooking, yelling');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image, interests) values ('bobRoss', '1234', 'Bob', 'Ross', 'Lorem ipsum dolor amet mlkshk venmo semiotics kitsch, fixie cliche ramps biodiesel iceland farm-to-table pitchfork la croix pinterest XOXO. Mustache VHS taiyaki green juice, small batch pok pok blue bottle pug aesthetic tilde trust fund locavore vape.', true, 'bob@ross.com', '419-419-8888', 'bobRoss', 'happy little trees');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image, interests) values('YoungSon', 1234, 'Jon', 'Snow', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', false, 'jonSnow@got.com', '419-706-0235', 'gh', 'java');

insert into subjects (subject_name, location, event_date, event_start_time, event_end_time, cost, available_slots, description) values ('Sword Fighting', 'Goodale Park', '10/25/2018', '10:00', '11:00', 25.0, 4, 'Learn to Slash Zombies');
insert into subjects (subject_name, location, event_date, event_start_time, event_end_time, cost, available_slots, description) values ('Civil Law', 'Eagles Island', '2018-11-02', '2:00', '4:00', 150.0, 5, 'Learn the steps to become a prominent litigator');
insert into subjects (subject_name, location, event_date, event_start_time, event_end_time, cost, available_slots, description) values ('Basic Car Mechanics', 'Tommys Garage', '2018-11-02', '2:00', '4:00', 50.0, 4, 'Learn all about brake pads');
insert into subjects (subject_name, location, event_date, event_start_time, event_end_time, cost, available_slots, description) values ('Scuba Diving', 'The Bellafountaine', '2018-09-02', '2:00', '4:00', 50.0, 8, 'Get ready for an under-water florescent adventure');
insert into subjects (subject_name, location, event_date, event_start_time, event_end_time, cost, available_slots, description) values ('Levitation', 'Dagoba', '2018-10-02', '12:00', '4:00', 0.0, 1, 'Do, or do not, this is no try. I will teach you the ways of the Force');
insert into subjects (subject_name, location, event_date, event_start_time, event_end_time, cost, available_slots, description) values ('Painting', 'Bobs Studio', '2018-12-02', '4:00', '8:00', 25.0, 6, 'Happy little mistakes everywhere');
insert into subjects (subject_name, location, event_date, event_start_time, event_end_time, cost, available_slots, description) values ('Martial Arts', 'The Turtle Pad', '2018-12-02', '4:00', '8:00', 25.0, 6, 'Learn the basics of martial arts, pizza provided after lesson');
insert into subjects (subject_name, location, event_date, event_start_time, event_end_time, cost, available_slots, description) values ('Cooking 101', 'Hells Kitchen', '2018-12-02', '4:00', '8:00', 25.0, 6, 'TIME TO COOK!!!!');


insert into user_subjects (class_id, user_name) values (1, 'lordgenius');



insert into messaging (message_to, message_from, message_subject, message_body, message_date_sent) values ('lordgenius', 'YoungSon', 'Hi', 'I have always wanted to kill zombies, teach me please!!!', '08/19/2018');

insert into reviews (reviewee, reviewer, panda_rating, review) values ('lordgenius', 'YoungSon', 5, 'lordgenius is both a lord and a genius, I slay zombies so hard now. I feel very confident in my survival skills and warmly welcome the coming apocalypse');

--sensei
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('otheraccount ',  'Qwerty1234', 'Kandace', 'Turner', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Kandace@Turner.com', '925-796-6870', ' grasshopper', 'Airbrushing');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('newact ',  'Qwerty1234', 'Eliseo', 'Phillips', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Eliseo@Phillips.com', '890-796-3269', ' grasshopper', 'Airsofting');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('goodadjustment ',  'Qwerty1234', 'Gwyn', 'Campbell', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Gwyn@Campbell.com', '665-095-4479', ' grasshopper', 'Acting');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('highadvertisement ',  'Qwerty1234', 'Gavin', 'Parker', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Gavin@Parker.com', '427-849-2611', ' grasshopper', 'Aeromodeling');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('oldagreement ',  'Qwerty1234', 'Maryalice', 'Evans', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Maryalice@Evans.com', '498-249-6741', ' grasshopper', 'Amateur Astronomy');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('greatair',  'Qwerty1234', 'Winifred', 'Edwards', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Winifred@Edwards.com', '640-368-5349', ' grasshopper', 'Bridge Building');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('bigamount',  'Qwerty1234', 'Felisa', 'Collins', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Felisa@Collins.com', '527-701-0870', ' grasshopper', 'Bringing Food To The Disabled');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('Americanamusement',  'Qwerty1234', 'Lanora', 'Stewart', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Lanora@Stewart.com', '521-820-6357', ' grasshopper', 'Building A House For Habitat For Humanity');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('smallanimal',  'Qwerty1234', 'Shandi', 'Sanchez', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Shandi@Sanchez.com', '441-723-3928', ' grasshopper', 'Building Dollhouses');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('largeanswer',  'Qwerty1234', 'Shenna', 'Morris', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Shenna@Morris.com', '370-025-9054', ' grasshopper', 'Butterfly Watching');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('nationalapparatus',  'Qwerty1234', 'Roberto', 'Rogers', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Roberto@Rogers.com', '770-720-2693', ' grasshopper', 'Button Collecting');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('youngapproval',  'Qwerty1234', 'Leatrice', 'Reed', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Leatrice@Reed.com', '477-419-3561', ' grasshopper', 'Cake Decorating');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('differentargument',  'Qwerty1234', 'Blanca', 'Cook', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Blanca@Cook.com', '407-639-6213', ' grasshopper', 'Calligraphy');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('blackart',  'Qwerty1234', 'Maricruz', 'Morgan', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Maricruz@Morgan.com', '980-667-4300', ' grasshopper', 'Camping');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('longattack',  'Qwerty1234', 'Rubye', 'Bell', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Rubye@Bell.com', '993-376-4328', ' grasshopper', 'Candle Making');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('littleattempt',  'Qwerty1234', 'Sherrell', 'Murphy', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Sherrell@Murphy.com', '585-091-0478', ' grasshopper', 'shooting rubber bands');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('importantattention',  'Qwerty1234', 'Pansy', 'Bailey', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Pansy@Bailey.com', '587-814-8910', ' grasshopper', 'Basketball');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('politicalattraction',  'Qwerty1234', 'Demetrice', 'Rivera', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Demetrice@Rivera.com', '864-307-4707', ' grasshopper', 'Beach/Sun tanning');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('badauthority',  'Qwerty1234', 'Bernice', 'Cooper', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Bernice@Cooper.com', '654-071-5261', ' grasshopper', 'Beachcombing');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('whiteback',  'Qwerty1234', 'Haydee', 'Richardson', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Haydee@Richardson.com', '984-825-0779', ' grasshopper', 'Beadwork');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('realbalance',  'Qwerty1234', 'Linn', 'Cox', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Linn@Cox.com', '466-117-9165', ' grasshopper', 'Beatboxing');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('bestbase',  'Qwerty1234', 'Norberto', 'Howard', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Norberto@Howard.com', '633-266-1213', ' grasshopper', 'Becoming A Child Advocate');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('rightbehavior',  'Qwerty1234', 'Bea', 'Ward', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Bea@Ward.com', '879-912-0261', ' grasshopper', 'Bell Ringing');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('socialbelief',  'Qwerty1234', 'Herma', 'Torres', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Herma@Torres.com', '664-385-3736', ' grasshopper', 'Belly Dancing');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('onlybirth',  'Qwerty1234', 'Andreas', 'Peterson', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Andreas@Peterson.com', '611-764-5125', ' grasshopper', 'Bicycling');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('publicbit',  'Qwerty1234', 'Fonda', 'Gray', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Fonda@Gray.com', '362-045-8781', ' grasshopper', 'Bicycle Polo');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('surebite',  'Qwerty1234', 'Christiana', 'Ramirez', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Christiana@Ramirez.com', '287-381-1845', ' grasshopper', 'Bird watching');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('lowblood',  'Qwerty1234', 'My', 'James', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'My@James.com', '314-849-9043', ' grasshopper', 'Birding');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('earlyblow',  'Qwerty1234', 'Irene', 'Watson', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Irene@Watson.com', '526-956-0700', ' grasshopper', 'BMX');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('ablebody',  'Qwerty1234', 'Laree', 'Brooks', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Laree@Brooks.com', '243-581-0313', ' grasshopper', 'Blacksmithing');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('humanbrass',  'Qwerty1234', 'Mohamed', 'Kelly', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Mohamed@Kelly.com', '626-418-5214', ' grasshopper', 'Blogging');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('localbread',  'Qwerty1234', 'Toby', 'Sanders', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Toby@Sanders.com', '484-889-9459', ' grasshopper', 'BoardGames');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('latebreath',  'Qwerty1234', 'Junko', 'Price', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Junko@Price.com', '992-043-4766', ' grasshopper', 'Boating');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('solidbrother',  'Qwerty1234', 'Margy', 'Bennett', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Margy@Bennett.com', '426-351-2043', ' grasshopper', 'Body Building');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('majorbuilding',  'Qwerty1234', 'Toney', 'Wood', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Toney@Wood.com', '441-284-5966', ' grasshopper', 'Bonsai Tree');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('betterburn',  'Qwerty1234', 'Nydia', 'Barnes', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Nydia@Barnes.com', '638-971-7020', ' grasshopper', 'Bookbinding');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('economicburst',  'Qwerty1234', 'Leonie', 'Roos', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Leonie@Roos.com', '942-009-4431', ' grasshopper', 'Boomerangs');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('strongbusiness',  'Qwerty1234', 'Candyce', 'Henderson', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Candyce@Henderson.com', '578-128-1604', ' grasshopper', 'Bowling');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('possiblebutter',  'Qwerty1234', 'Kizzie', 'Coleman', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Kizzie@Coleman.com', '640-932-1248', ' grasshopper', 'Brewing Beer');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('wholecanvas',  'Qwerty1234', 'Dorie', 'Jenkins', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Dorie@Jenkins.com', '743-389-6301', ' grasshopper', 'Bridge Building');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('freecare',  'Qwerty1234', 'Earleen', 'Perry', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Earleen@Perry.com', '937-438-1882', ' grasshopper', 'Bringing Food To The Disabled');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('militarycause',  'Qwerty1234', 'Carlo', 'Powell', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Carlo@Powell.com', '332-246-1963', ' grasshopper', 'Building A House For Habitat For Humanity');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('TRUEchalk',  'Qwerty1234', 'Ardith', 'Long', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Ardith@Long.com', '561-746-9137', ' grasshopper', 'Building Dollhouses');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('federalchance',  'Qwerty1234', 'Ta', 'Patterson', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Ta@Patterson.com', '470-091-1188', ' grasshopper', 'Butterfly Watching');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('internationalchange',  'Qwerty1234', 'Valentine', 'Hughes', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Valentine@Hughes.com', '538-248-9262', ' grasshopper', 'Button Collecting');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('fullcloth',  'Qwerty1234', 'Novella', 'Flores', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Novella@Flores.com', '953-639-9720', ' grasshopper', 'Cake Decorating');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('specialcoal',  'Qwerty1234', 'Joyce', 'Washington', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Joyce@Washington.com', '556-688-0389', ' grasshopper', 'Calligraphy');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('easycolor',  'Qwerty1234', 'Franklin', 'Butler', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Franklin@Butler.com', '857-285-7085', ' grasshopper', 'Camping');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('clearcomfort',  'Qwerty1234', 'Nelida', '  Simmons', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Nelida@  Simmons.com', '823-768-7700', ' grasshopper', 'Candle Making');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('recenthouse',  'Qwerty1234', 'Cathey', '  Foster', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', TRUE, 'Cathey@  Foster.com', '288-525-5134', ' grasshopper', 'shooting rubber bands');
--grasshopper
insert into user_info (user_name,  password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('ableWord',  'Qwerty1234', 'Tamera', 'SMITH', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Tamera@SMITH.com', ' 854-302-6064', 'grasshopper', 'Airbrushing');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('badpeople',  'Qwerty1234', 'Katia', 'JONES', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Katia@JONES.com', ' 869-293-1705', 'grasshopper', 'Airsofting');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('besthistory',  'Qwerty1234', 'Garrett', 'BROWN', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Garrett@BROWN.com', ' 284-947-2984', 'grasshopper', 'Acting');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('betterway',  'Qwerty1234', 'Mickey', 'JOHNSON', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Mickey@JOHNSON.com', ' 631-457-9372', 'grasshopper', 'Aeromodeling');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('bigart',  'Qwerty1234', 'Markus', 'WILLIAMS', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Markus@WILLIAMS.com', ' 736-211-4249', 'grasshopper', 'Amateur Astronomy');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('blackworld',  'Qwerty1234', 'Ignacia', 'MILLER', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Ignacia@MILLER.com', ' 498-623-7108', 'grasshopper', 'Amateur Radio');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('certaininformation',  'Qwerty1234', 'Latoya', 'TAYLOR', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Latoya@TAYLOR.com', ' 702-292-3711', 'grasshopper', 'Animals/pets/dogs');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('clearmap',  'Qwerty1234', 'Chrystal', 'WILSON', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Chrystal@WILSON.com', ' 692-959-9354', 'grasshopper', 'Archery');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('differenttwo',  'Qwerty1234', 'Claire', 'DAVIS', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Claire@DAVIS.com', ' 768-010-4008', 'grasshopper', 'Arts');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('earlyfamily',  'Qwerty1234', 'Brigida', 'WHITE', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Brigida@WHITE.com', ' 775-879-7020', 'grasshopper', 'Aquarium (Freshwater & Saltwater)');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('easygovernment',  'Qwerty1234', 'Gaye', 'CLARK', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Gaye@CLARK.com', ' 928-600-9824', 'grasshopper', 'Astrology');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('economichealth',  'Qwerty1234', 'Sebastian', 'HALL', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Sebastian@HALL.com', ' 711-800-5283', 'grasshopper', 'Astronomy');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('federalsystem',  'Qwerty1234', 'Micha', 'THOMAS', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Micha@THOMAS.com', ' 731-441-6095', 'grasshopper', 'Backgammon');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('freecomputer',  'Qwerty1234', 'Lazaro', 'THOMPSON', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Lazaro@THOMPSON.com', ' 646-073-7743', 'grasshopper', 'Badminton');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('fullmeat',  'Qwerty1234', 'Lauran', 'MOORE', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Lauran@MOORE.com', ' 501-343-5376', 'grasshopper', 'Baseball');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('goodyear',  'Qwerty1234', 'Tiffanie', 'HILL', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Tiffanie@HILL.com', ' 764-750-2890', 'grasshopper', 'Base Jumping');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('greatthanks',  'Qwerty1234', 'Pamela', 'WALKER', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Pamela@WALKER.com', ' 628-768-7595', 'grasshopper', 'Basketball');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('hardmusic',  'Qwerty1234', 'Myong', 'ANDERSON', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Myong@ANDERSON.com', ' 888-631-3469', 'grasshopper', 'Beach/Sun tanning');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('highperson',  'Qwerty1234', 'Catrice', 'WRIGHT', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Catrice@WRIGHT.com', ' 863-841-8053', 'grasshopper', 'Beachcombing');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('humanreading',  'Qwerty1234', 'Cuc', 'MARTIN', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Cuc@MARTIN.com', ' 692-746-1065', 'grasshopper', 'Beadwork');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('importantmethod',  'Qwerty1234', 'Neomi', 'WOOD', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Neomi@WOOD.com', ' 282-718-7128', 'grasshopper', 'Beatboxing');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('internationaldata',  'Qwerty1234', 'Erick', 'ALLEN', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Erick@ALLEN.com', ' 898-641-3172', 'grasshopper', 'Becoming A Child Advocate');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('largefood',  'Qwerty1234', 'Sandi', 'ROBINSON', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Sandi@ROBINSON.com', ' 277-691-8250', 'grasshopper', 'Bell Ringing');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('lateunderstanding',  'Qwerty1234', 'Dario', 'LEWIS', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Dario@LEWIS.com', ' 993-869-1126', 'grasshopper', 'Belly Dancing');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('littletheory',  'Qwerty1234', 'Solange', 'BAKER', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Solange@BAKER.com', ' 359-771-5417', 'grasshopper', 'Bicycling');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('locallaw',  'Qwerty1234', 'Thresa', 'JOHN', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Thresa@JOHN.com', ' 755-372-1914', 'grasshopper', 'Bicycle Polo');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('longbird',  'Qwerty1234', 'Holley', 'HARRIS', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Holley@HARRIS.com', ' 522-258-9737', 'grasshopper', 'Bird watching');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('lowliterature',  'Qwerty1234', 'Mafalda', 'ROBERTS', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Mafalda@ROBERTS.com', ' 394-545-6300', 'grasshopper', 'Birding');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('majorproblem',  'Qwerty1234', 'Scotty', 'CAMPBELL', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Scotty@CAMPBELL.com', ' 893-505-6517', 'grasshopper', 'BMX');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('militarysoftware',  'Qwerty1234', 'Kimbery', 'JAMES', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Kimbery@JAMES.com', ' 373-102-7980', 'grasshopper', 'Blacksmithing');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('nationalcontrol',  'Qwerty1234', 'Thersa', 'STEWART', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Thersa@STEWART.com', ' 393-070-7223', 'grasshopper', 'Blogging');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('newknowledge',  'Qwerty1234', 'Veola', 'LEE', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Veola@LEE.com', ' 952-225-7648', 'grasshopper', 'BoardGames');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('oldpower',  'Qwerty1234', 'Phillip', 'COUNTY', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Phillip@COUNTY.com', ' 425-591-2298', 'grasshopper', 'Boating');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('onlyability',  'Qwerty1234', 'Marline', 'TURNER', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Marline@TURNER.com', ' 623-877-3532', 'grasshopper', 'Body Building');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('othereconomics',  'Qwerty1234', 'Mollie', 'PARKER', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Mollie@PARKER.com', ' 538-421-1878', 'grasshopper', 'Bonsai Tree');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('politicallove',  'Qwerty1234', 'Lakenya', 'COOK', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Lakenya@COOK.com', ' 503-007-7367', 'grasshopper', 'Bookbinding');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('possibleinternet',  'Qwerty1234', 'Anita', 'MC', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Anita@MC.com', ' 307-052-8680', 'grasshopper', 'Boomerangs');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('publictelevision',  'Qwerty1234', 'Ebony', 'EDWARDS', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Ebony@EDWARDS.com', ' 406-740-7062', 'grasshopper', 'Bowling');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('realscience',  'Qwerty1234', 'Fleta', 'MORRIS', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Fleta@MORRIS.com', ' 943-001-2863', 'grasshopper', 'Brewing Beer');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('recentlibrary',  'Qwerty1234', 'Herschel', 'MITCHELL', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Herschel@MITCHELL.com', ' 762-407-5369', 'grasshopper', 'Bridge Building');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('rightnature',  'Qwerty1234', 'Landon', 'BELL', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Landon@BELL.com', ' 984-963-8298', 'grasshopper', 'Bringing Food To The Disabled');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('smallfact',  'Qwerty1234', 'Lorrine', 'WARD', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Lorrine@WARD.com', ' 669-237-1503', 'grasshopper', 'Building A House For Habitat For Humanity');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('socialproduct',  'Qwerty1234', 'Eugena', 'WATSON', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Eugena@WATSON.com', ' 514-864-9105', 'grasshopper', 'Building Dollhouses');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('specialidea',  'Qwerty1234', 'Linnea', 'MORGAN', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Linnea@MORGAN.com', ' 711-282-5219', 'grasshopper', 'Butterfly Watching');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('strongtemperature',  'Qwerty1234', 'Kelle', 'DAVIES', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Kelle@DAVIES.com', ' 509-099-5846', 'grasshopper', 'Button Collecting');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('sureinvestment',  'Qwerty1234', 'Verda', 'COOPER', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Verda@COOPER.com', ' 913-885-4172', 'grasshopper', 'Cake Decorating');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('TRUEarea',  'Qwerty1234', 'Wilbur', 'PHILLIPS', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Wilbur@PHILLIPS.com', ' 723-545-8213', 'grasshopper', 'Calligraphy');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('whitesociety',  'Qwerty1234', 'Sierra', 'ROGERS', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Sierra@ROGERS.com', ' 710-146-5649', 'grasshopper', 'Camping');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('wholeactivity',  'Qwerty1234', 'Sharda', 'GRAY', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Sharda@GRAY.com', ' 591-811-0190', 'grasshopper', 'Candle Making');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image,  interests) values('oldstory',  'Qwerty1234', 'Dena', 'HUGHES', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', FALSE, 'Dena@HUGHES.com', ' 341-075-6126', 'grasshopper', 'Jumping Jacks');

insert into user_subjects (class_id, user_name) values (2, 'royalTenenbaum');
insert into user_subjects (class_id, user_name) values (3, 'tommyBoy');
insert into user_subjects (class_id, user_name) values (4, 'steveZissou');
insert into user_subjects (class_id, user_name) values (5, 'lukeSkywalker');
insert into user_subjects (class_id, user_name) values (6, 'bobRoss');
insert into user_subjects (class_id, user_name) values (7, 'splinter');
insert into user_subjects (class_id, user_name) values (8, 'gordonRamsey');
insert into user_subjects (class_id, user_name) values (2, 'freecare');
insert into user_subjects (class_id, user_name) values (3, 'fullcloth');
insert into user_subjects (class_id, user_name) values (4, 'clearcomfort');
insert into user_subjects (class_id, user_name) values (5, 'easycolor');
insert into user_subjects (class_id, user_name) values (6, 'wholecanvas');
insert into user_subjects (class_id, user_name) values (7, 'lordgenius');
insert into user_subjects (class_id, user_name) values (8, 'tommyBoy');
insert into user_subjects (class_id, user_name) values (1, 'lukeSkywalker');

insert into reviews (reviewee, reviewer, panda_rating, review) values ('lukeSkywalker', 'YoungSon', 4, 'Great jedi knight, ok sword fighter');












