-- *****************************************************************************
-- This script contains INSERT statements for populating tables with seed data
-- *****************************************************************************

insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image, interests) values ('lordgenius', '1234', 'Gordy', 'Smith', 'Lorem ipsum dolor amet mlkshk venmo semiotics kitsch, fixie cliche ramps biodiesel iceland farm-to-table pitchfork la croix pinterest XOXO. Mustache VHS taiyaki green juice, small batch pok pok blue bottle pug aesthetic tilde trust fund locavore vape.', true, 'gordy@swordfighting.com', '614-555-3456', 'sensei', 'zombies');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image, interests) values ('tommyBoy', '1234', 'Tommy', 'Callahan', 'Lorem ipsum dolor amet mlkshk venmo semiotics kitsch, fixie cliche ramps biodiesel iceland farm-to-table pitchfork la croix pinterest XOXO. Mustache VHS taiyaki green juice, small batch pok pok blue bottle pug aesthetic tilde trust fund locavore vape.', true, 'tommy@callahan.com', '419-419-0000', 'tommy', 'road trips');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image, interests) values ('happyGilmore', '1234', 'Happy', 'Gilmore', 'Lorem ipsum dolor amet mlkshk venmo semiotics kitsch, fixie cliche ramps biodiesel iceland farm-to-table pitchfork la croix pinterest XOXO. Mustache VHS taiyaki green juice, small batch pok pok blue bottle pug aesthetic tilde trust fund locavore vape.', false, 'happy@gilmore.com', '419-419-0000', 'happy', 'golf');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image, interests) values ('royalTenenbaum', '1234', 'Royal', 'Tenenbaum', 'Lorem ipsum dolor amet mlkshk venmo semiotics kitsch, fixie cliche ramps biodiesel iceland farm-to-table pitchfork la croix pinterest XOXO. Mustache VHS taiyaki green juice, small batch pok pok blue bottle pug aesthetic tilde trust fund locavore vape.', true, 'royal@tenebaum.com', '419-419-1111', 'royal', 'prominent litigation');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image, interests) values ('steveZissou', '1234', 'Stevesy', 'Zissou', 'Lorem ipsum dolor amet mlkshk venmo semiotics kitsch, fixie cliche ramps biodiesel iceland farm-to-table pitchfork la croix pinterest XOXO. Mustache VHS taiyaki green juice, small batch pok pok blue bottle pug aesthetic tilde trust fund locavore vape.', true, 'steve@zissou.com', '419-419-2222', 'stevesy', 'scuba-diving');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image, interests) values ('lukeSkywalker', '1234', 'Luke', 'Skywalker', 'Lorem ipsum dolor amet mlkshk venmo semiotics kitsch, fixie cliche ramps biodiesel iceland farm-to-table pitchfork la croix pinterest XOXO. Mustache VHS taiyaki green juice, small batch pok pok blue bottle pug aesthetic tilde trust fund locavore vape.', true, 'luke@jediKnights.com', '419-419-3333', 'skywalker', 'father-son time');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image, interests) values ('billyMadison', '1234', 'Billy', 'Madison', 'Lorem ipsum dolor amet mlkshk venmo semiotics kitsch, fixie cliche ramps biodiesel iceland farm-to-table pitchfork la croix pinterest XOXO. Mustache VHS taiyaki green juice, small batch pok pok blue bottle pug aesthetic tilde trust fund locavore vape.', false, 'billy@madison.com', '419-419-4444', 'madison', 'gen-ed, penguins');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image, interests) values ('splinter', '1234', 'Splinter', 'Rat', 'Lorem ipsum dolor amet mlkshk venmo semiotics kitsch, fixie cliche ramps biodiesel iceland farm-to-table pitchfork la croix pinterest XOXO. Mustache VHS taiyaki green juice, small batch pok pok blue bottle pug aesthetic tilde trust fund locavore vape.', true, 'splinter@sewers.com', '419-419-5555', 'splinter', 'martial arts');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image, interests) values ('danielSon', '1234', 'Daniel', 'Son', 'Lorem ipsum dolor amet mlkshk venmo semiotics kitsch, fixie cliche ramps biodiesel iceland farm-to-table pitchfork la croix pinterest XOXO. Mustache VHS taiyaki green juice, small batch pok pok blue bottle pug aesthetic tilde trust fund locavore vape.', false, 'daniel@son.com', '419-419-6666', 'danielSon', 'karate');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image, interests) values ('gordonRamsey', '1234', 'Gordon', 'Ramsey', 'Lorem ipsum dolor amet mlkshk venmo semiotics kitsch, fixie cliche ramps biodiesel iceland farm-to-table pitchfork la croix pinterest XOXO. Mustache VHS taiyaki green juice, small batch pok pok blue bottle pug aesthetic tilde trust fund locavore vape.', true, 'gordon@ramsey.com', '419-419-7777', 'gordonRamsey', 'cooking, yelling');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image, interests) values ('bobRoss', '1234', 'Bob', 'Ross', 'Lorem ipsum dolor amet mlkshk venmo semiotics kitsch, fixie cliche ramps biodiesel iceland farm-to-table pitchfork la croix pinterest XOXO. Mustache VHS taiyaki green juice, small batch pok pok blue bottle pug aesthetic tilde trust fund locavore vape.', true, 'bob@ross.com', '419-419-8888', 'bobRoss', 'happy little trees');
insert into user_info (user_name, password, first_name, last_name, bio, is_sensei, email, phone, profile_image, interests) values('YoungSon', 1234, 'Jon', 'Snow', 'Lorem ipsum dolor amet migas retro shabby chic, hot chicken vice hell of health goth before they sold out irony. Retro pop-up raclette cornhole YOLO lomo. Gluten-free waistcoat la croix, skateboard organic pabst dreamcatcher pok pok adaptogen direct trade wayfarers art party', false, 'jonSnow@got.com', '419-706-0235', 'gh', 'java');

insert into subjects (subject_name, location, event_date, event_start_time, event_end_time, cost, available_slots, description) values ('Sword Fighting', 'Goodale Park', '10/25/2018', '10:00', '11:00', 25.0, 4, 'Learn to Slash Zombies');
insert into subjects (subject_name, location, event_date, event_start_time, event_end_time, cost, available_slots, description) values ('Civil Law', 'Eagles Island', '2018-11-02', '2:00', '4:00', 150.0, 5, 'Learn the steps to become a prominent litigator');
insert into subjects (subject_name, location, event_date, event_start_time, event_end_time, cost, available_slots, description) values ('Basic Car Mechanics', 'Tommys Garage', '2018-11-02', '2:00', '4:00', 50.0, 4, 'Learn all about brake pads');
insert into subjects (subject_name, location, event_date, event_start_time, event_end_time, cost, available_slots, description) values ('Scuba Diving', 'The Bellafountaine', '2018-09-02', '2:00', '4:00', 50.0, 8, 'Get ready for an under-water florescent adventure');
insert into subjects (subject_name, location, event_date, event_start_time, event_end_time, cost, available_slots, description) values ('Levitation', 'Dagoba', '2018-10-02', '12:00', '4:00', 0.0, 1, 'Do, or do not, this is no try. I will teach you the ways of the Force');
insert into subjects (subject_name, location, event_date, event_start_time, event_end_time, cost, available_slots, description) values ('Painting', 'Bobs Studio', '2018-12-02', '4:00', '8:00', 25.0, 6, 'Happy little mistakes everywhere');
insert into subjects (subject_name, location, event_date, event_start_time, event_end_time, cost, available_slots, description) values ('Martial Arts', 'The Turtle Pad', '2018-12-02', '4:00', '8:00', 25.0, 6, 'Learn the basics of martial arts, pizza provided after lesson');
insert into subjects (subject_name, location, event_date, event_start_time, event_end_time, cost, available_slots, description) values ('Cooking 101', 'Hells Kitchen', '2018-12-02', '4:00', '8:00', 25.0, 6, 'TIME TO COOK!!!!');


insert into user_subjects (class_id, user_name) values (1, 'lordgenius');



insert into messaging (message_to, message_from, message_subject, message_body, message_date_sent) values ('lordgenius', 'YoungSon', 'Hi', 'I have always wanted to kill zombies, teach me please!!!', '08/19/2018');

insert into reviews (reviewee, reviewer, panda_rating, review) values ('lordgenius', 'YoungSon', 5, 'lordgenius is both a lord and a genius, I slay zombies so hard now. I feel very confident in my survival skills and warmly welcome the coming apocalypse')

